version: '2'
services:
  app-flask:
    image: openchemistry/stemserver:latest
    labels:
      io.rancher.container.pull_image: always
    retain_ip: true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    ports:
          - 50049:5000

  web-nginx:
    image: openchemistry/stemclient:latest
    labels:
      io.rancher.container.pull_image: always
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
      - NET_BIND_SERVICE
    group_add:
      - nginx
    links:
      - app-flask
    depends_on:
      - app-flask
    ports:
          - 60048:80

